version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ server
      - "15672:15672" # Management Console
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

  driver-service:
    build: ./driver-service
    container_name: driver-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  rider-service:
    build: ./rider-service
    container_name: rider-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  websocket-service:
    build: ./websocket-service
    container_name: websocket-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
